---
- name: Instal gitlab
  hosts: gitlab
  become: true

  roles:
      - { role: gitlab }
# - name: Install redis
#   hosts: redis_server
#   become: true

#   roles:
#       - { role: redis }

# - name: Install Minio
#   hosts: minio
#   become: yes
#   roles:
#       - { role: minio }

# - name: Install Docker on Ubuntu
#   hosts: docker
#   become: true
#   vars:
#       arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
#           x86_64: amd64
#           aarch64: arm64
#   roles:
#       - { role: docker }

# - name: Install postgres database
#   hosts: postgres_db
#   become: true

#   roles:
#       - { role: postgres_db }
